export interface DictationSentence {
  id: number;
  text: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const SENTENCES: DictationSentence[] = [
  // ─── EASY (3-5 words) ─────────────────────────
  { id: 1, text: 'Le chat dort.', difficulty: 'easy' },
  { id: 2, text: 'Il fait beau.', difficulty: 'easy' },
  { id: 3, text: 'Je mange une pomme.', difficulty: 'easy' },
  { id: 4, text: 'Le soleil brille.', difficulty: 'easy' },
  { id: 5, text: 'Elle aime les fleurs.', difficulty: 'easy' },
  { id: 6, text: 'Mon chien est gentil.', difficulty: 'easy' },
  { id: 7, text: 'Le livre est rouge.', difficulty: 'easy' },
  { id: 8, text: 'Papa fait un gâteau.', difficulty: 'easy' },
  { id: 9, text: 'Les oiseaux chantent.', difficulty: 'easy' },
  { id: 10, text: 'Je suis content.', difficulty: 'easy' },
  { id: 11, text: 'La lune est ronde.', difficulty: 'easy' },
  { id: 12, text: 'Il pleut dehors.', difficulty: 'easy' },
  { id: 13, text: 'Le bébé rit.', difficulty: 'easy' },
  { id: 14, text: 'Maman lit un livre.', difficulty: 'easy' },
  { id: 15, text: 'La porte est ouverte.', difficulty: 'easy' },
  { id: 16, text: 'Le train arrive.', difficulty: 'easy' },
  { id: 17, text: 'Il neige beaucoup.', difficulty: 'easy' },
  { id: 18, text: 'Le chien court vite.', difficulty: 'easy' },
  { id: 19, text: 'Ma sœur chante bien.', difficulty: 'easy' },
  { id: 20, text: 'Le ciel est bleu.', difficulty: 'easy' },
  { id: 21, text: 'La voiture est verte.', difficulty: 'easy' },
  { id: 22, text: 'Il mange du pain.', difficulty: 'easy' },
  { id: 23, text: 'Elle joue dehors.', difficulty: 'easy' },
  { id: 24, text: 'Le poisson nage.', difficulty: 'easy' },
  { id: 25, text: 'Mon chat est noir.', difficulty: 'easy' },
  { id: 26, text: 'Il dort bien.', difficulty: 'easy' },
  { id: 27, text: 'La table est grande.', difficulty: 'easy' },
  { id: 28, text: 'Le garçon sourit.', difficulty: 'easy' },
  { id: 29, text: 'La fille danse.', difficulty: 'easy' },
  { id: 30, text: 'Je bois du lait.', difficulty: 'easy' },
  { id: 31, text: 'Papa est grand.', difficulty: 'easy' },
  { id: 32, text: 'Le ballon est rond.', difficulty: 'easy' },
  { id: 33, text: 'Elle court très vite.', difficulty: 'easy' },
  { id: 34, text: 'La pomme est rouge.', difficulty: 'easy' },
  { id: 35, text: 'Mon frère est petit.', difficulty: 'easy' },
  { id: 36, text: 'Il fait très froid.', difficulty: 'easy' },
  { id: 37, text: 'La maison est belle.', difficulty: 'easy' },
  { id: 38, text: 'Le vélo est bleu.', difficulty: 'easy' },
  { id: 39, text: 'Nous sommes contents.', difficulty: 'easy' },
  { id: 40, text: 'Le lapin mange.', difficulty: 'easy' },

  // ─── MEDIUM (6-10 words) ───────────────────────
  { id: 41, text: 'Le petit garçon joue dans le jardin.', difficulty: 'medium' },
  { id: 42, text: 'Ma sœur aime beaucoup les fraises rouges.', difficulty: 'medium' },
  { id: 43, text: 'Les enfants courent dans la cour de récréation.', difficulty: 'medium' },
  { id: 44, text: 'Le chat noir dort sur le canapé.', difficulty: 'medium' },
  { id: 45, text: 'Nous allons à la plage cet été.', difficulty: 'medium' },
  { id: 46, text: 'Le chien aboie quand il voit le facteur.', difficulty: 'medium' },
  { id: 47, text: 'Elle dessine une maison avec un grand jardin.', difficulty: 'medium' },
  { id: 48, text: 'Les étoiles brillent dans le ciel noir.', difficulty: 'medium' },
  { id: 49, text: 'Mon frère joue de la guitare le soir.', difficulty: 'medium' },
  { id: 50, text: 'La maîtresse écrit la leçon au tableau.', difficulty: 'medium' },
  { id: 51, text: 'Le vent souffle fort dans les arbres.', difficulty: 'medium' },
  { id: 52, text: 'Je prends mon petit déjeuner tous les matins.', difficulty: 'medium' },
  { id: 53, text: 'Les poissons nagent dans la rivière claire.', difficulty: 'medium' },
  { id: 54, text: 'Ma mère prépare une soupe aux légumes.', difficulty: 'medium' },
  { id: 55, text: 'Le facteur apporte le courrier chaque matin.', difficulty: 'medium' },
  { id: 56, text: 'Les canards nagent sur le lac tranquille.', difficulty: 'medium' },
  { id: 57, text: 'Mon père répare la voiture dans le garage.', difficulty: 'medium' },
  { id: 58, text: 'La petite fille ramasse des coquillages sur la plage.', difficulty: 'medium' },
  { id: 59, text: 'Le jardinier arrose les fleurs du parc.', difficulty: 'medium' },
  { id: 60, text: 'Nous regardons un film ensemble ce soir.', difficulty: 'medium' },
  { id: 61, text: 'Les nuages blancs traversent le ciel bleu.', difficulty: 'medium' },
  { id: 62, text: 'Le boulanger vend du pain et des croissants.', difficulty: 'medium' },
  { id: 63, text: 'Ma grand-mère tricote une écharpe en laine.', difficulty: 'medium' },
  { id: 64, text: 'Les hirondelles reviennent au printemps chaque année.', difficulty: 'medium' },
  { id: 65, text: 'Le docteur soigne les malades à l\'hôpital.', difficulty: 'medium' },
  { id: 66, text: 'Nous jouons au ballon dans le parc.', difficulty: 'medium' },
  { id: 67, text: 'La neige recouvre les toits des maisons.', difficulty: 'medium' },
  { id: 68, text: 'Il dessine un bateau sur une feuille blanche.', difficulty: 'medium' },
  { id: 69, text: 'Les abeilles fabriquent du miel dans la ruche.', difficulty: 'medium' },
  { id: 70, text: 'Mon cousin habite dans une grande ville.', difficulty: 'medium' },
  { id: 71, text: 'Le pompier éteint le feu avec la lance.', difficulty: 'medium' },
  { id: 72, text: 'La tortue avance lentement sur le chemin.', difficulty: 'medium' },
  { id: 73, text: 'Les feuilles tombent des arbres en automne.', difficulty: 'medium' },
  { id: 74, text: 'Elle range sa chambre avant de sortir.', difficulty: 'medium' },
  { id: 75, text: 'Le soleil se couche derrière la montagne.', difficulty: 'medium' },
  { id: 76, text: 'Papa nous emmène au cinéma ce samedi.', difficulty: 'medium' },
  { id: 77, text: 'Les lapins mangent des carottes dans le potager.', difficulty: 'medium' },
  { id: 78, text: 'Le pirate cherche un trésor sur une île.', difficulty: 'medium' },
  { id: 79, text: 'Ma tante prépare un repas pour toute la famille.', difficulty: 'medium' },
  { id: 80, text: 'Le hibou chasse la nuit dans la forêt.', difficulty: 'medium' },

  // ─── HARD (11+ words) ──────────────────────────
  { id: 81, text: 'Pendant les vacances, nous avons visité un très beau château.', difficulty: 'hard' },
  { id: 82, text: 'Le petit prince a découvert une rose magnifique sur sa planète.', difficulty: 'hard' },
  { id: 83, text: 'Les papillons multicolores volent au-dessus des fleurs du jardin.', difficulty: 'hard' },
  { id: 84, text: 'Ma grand-mère prépare toujours de délicieux gâteaux au chocolat.', difficulty: 'hard' },
  { id: 85, text: 'Les élèves de la classe ont organisé une fête pour la fin de l\'année.', difficulty: 'hard' },
  { id: 86, text: 'Le renard rusé se cache derrière le buisson pour observer les poules.', difficulty: 'hard' },
  { id: 87, text: 'Chaque matin, les oiseaux chantent une mélodie joyeuse dans les arbres.', difficulty: 'hard' },
  { id: 88, text: 'La bibliothèque de l\'école contient des centaines de livres passionnants.', difficulty: 'hard' },
  { id: 89, text: 'Mon meilleur ami et moi aimons construire des cabanes dans la forêt.', difficulty: 'hard' },
  { id: 90, text: 'Le boulanger se lève très tôt pour préparer le pain et les croissants.', difficulty: 'hard' },
  { id: 91, text: 'Après la pluie, un magnifique arc-en-ciel est apparu dans le ciel.', difficulty: 'hard' },
  { id: 92, text: 'Les astronautes voyagent dans l\'espace pour découvrir de nouvelles planètes.', difficulty: 'hard' },
  { id: 93, text: 'Le petit écureuil ramasse des noisettes pour les garder pendant l\'hiver.', difficulty: 'hard' },
  { id: 94, text: 'Le capitaine du bateau observe la mer avec ses grandes jumelles.', difficulty: 'hard' },
  { id: 95, text: 'Les enfants construisent un bonhomme de neige dans le jardin enneigé.', difficulty: 'hard' },
  { id: 96, text: 'La princesse traverse la forêt enchantée pour retrouver son château.', difficulty: 'hard' },
  { id: 97, text: 'Mon grand-père raconte des histoires passionnantes quand nous allons le voir.', difficulty: 'hard' },
  { id: 98, text: 'Les dauphins jouent dans les vagues bleues de l\'océan Atlantique.', difficulty: 'hard' },
  { id: 99, text: 'Le professeur explique la leçon de mathématiques avec beaucoup de patience.', difficulty: 'hard' },
  { id: 100, text: 'Nous avons planté des tomates et des courgettes dans le potager familial.', difficulty: 'hard' },
  { id: 101, text: 'Le chevalier courageux part à la recherche du dragon qui terrorise le village.', difficulty: 'hard' },
  { id: 102, text: 'Les musiciens de l\'orchestre répètent tous les jours pour le concert de samedi.', difficulty: 'hard' },
  { id: 103, text: 'La petite souris se faufile sous la porte pour grignoter le fromage.', difficulty: 'hard' },
  { id: 104, text: 'Pendant la récréation, les enfants jouent à cache-cache derrière les arbres.', difficulty: 'hard' },
  { id: 105, text: 'Le scientifique observe les étoiles avec un énorme télescope depuis la colline.', difficulty: 'hard' },
  { id: 106, text: 'Ma famille et moi partons en vacances à la montagne pour faire du ski.', difficulty: 'hard' },
  { id: 107, text: 'Le peintre mélange les couleurs sur sa palette pour créer un tableau magnifique.', difficulty: 'hard' },
  { id: 108, text: 'Les tortues de mer pondent leurs œufs sur les plages de sable chaud.', difficulty: 'hard' },
  { id: 109, text: 'Le magicien sort un lapin blanc de son chapeau devant tous les spectateurs.', difficulty: 'hard' },
  { id: 110, text: 'Chaque dimanche, nous allons nous promener dans la forêt avec notre chien.', difficulty: 'hard' },
  { id: 111, text: 'Le cuisinier prépare un repas délicieux avec des légumes frais du marché.', difficulty: 'hard' },
  { id: 112, text: 'Les explorateurs découvrent une grotte secrète remplie de cristaux brillants.', difficulty: 'hard' },
  { id: 113, text: 'Ma petite sœur apprend à faire du vélo sans les petites roues.', difficulty: 'hard' },
  { id: 114, text: 'Le fermier conduit son tracteur dans les champs pour récolter le blé.', difficulty: 'hard' },
  { id: 115, text: 'Les élèves préparent un spectacle de fin d\'année avec des chansons et des danses.', difficulty: 'hard' },
  { id: 116, text: 'Le photographe prend de belles photos des animaux sauvages dans la savane.', difficulty: 'hard' },
  { id: 117, text: 'Nous avons construit une cabane en bois au fond du jardin de mes grands-parents.', difficulty: 'hard' },
  { id: 118, text: 'Le pilote d\'avion survole les montagnes enneigées avant d\'atterrir à l\'aéroport.', difficulty: 'hard' },
  { id: 119, text: 'Les grenouilles coassent au bord de la mare quand la nuit commence à tomber.', difficulty: 'hard' },
  { id: 120, text: 'Le vétérinaire soigne les animaux blessés et leur donne des médicaments.', difficulty: 'hard' },
];

export function getSentences(difficulty: 'easy' | 'medium' | 'hard'): DictationSentence[] {
  return SENTENCES.filter((s) => s.difficulty === difficulty);
}

export function getRandomSentence(difficulty: 'easy' | 'medium' | 'hard', excludeIds: number[]): DictationSentence | null {
  const available = SENTENCES.filter((s) => s.difficulty === difficulty && !excludeIds.includes(s.id));
  if (available.length === 0) return null;
  return available[Math.floor(Math.random() * available.length)]!;
}
